### ISSUE TITLE
ValueError: Input strings must be a multiple of 8 in length

### ISSUE THREAD

**Issue by aminehmida** [peppelinux/Remmina-password-exposer#1]
Traceback (most recent call last):
  File "remmina_password_exposer.py", line 47, in <module>
    diz[r_name] = DES3.new(secret[:24], DES3.MODE_CBC, secret[24:]).decrypt(password)
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 8 in length

**Comment by peppelinux** [comment]
MMhh... I never seen an exception like that.
Is this script never worked for you ?

**Comment by pauldraper** [comment]
I also have this error.

But it did print out the password before it crashed.

**Comment by pauldraper** [comment]
Ah, I had a `.1462480944457.remmina.swp` file, and it barfed because of that.

**Comment by peppelinux** [comment]
I need to know remmina version and `lsb_release -a`.

If .swp file is needed we could patch it extending the regexp constant from
REGEXP_ACCOUNTS = r'[0-9]{13}.remmina'
to
REGEXP_ACCOUNTS = r'[0-9]{13}.remmina(.swp)?'

I made a new commit on it, please try and let me know
