### ISSUE TITLE
ValueError: Input strings must be a multiple of 8 in length when having RD Gateway set

### ISSUE THREAD

**Issue by sedasek** [peppelinux/Remmina-password-exposer#3]
Hey there,  

First, thanks for the script. There's a potential issue if the RD gateway server is used and has a password set. Then the line 
`if re.findall(r'password=', i):  `
can wrongly match with the RD gateway password line, e.g.:
`gateway_password=Kps+XXXXXXXXXXXXXXXXXXX==`

Including a match for the beginning of the line in the RE helps to prevent that:
`if re.findall(r'^password=', i):  `

Cheers.

**Comment by peppelinux** [comment]
Thank you sedasek,
I patched it, you can always do a pull request if needed.
