### ISSUE TITLE
Remmina accounts aren't necessarily in the remmina perferences folder.

### ISSUE THREAD

**Issue by h6w** [peppelinux/Remmina-password-exposer#4]
Like the title says.  On Ubuntu 18.10, the Remmina folder is `~/.config/remmina`  but all the accounts with *.remmina are in `~/.local/share/remmina`.

**Comment by peppelinux** [comment]
Thank you,
as written in the README.md you can specificy folder this way:
`REMMINA_FOLDER=~/.local/share/remmina remmina_password_exposer.py`
